/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjectshowImport } from './routes/projectshow'
import { Route as ProjectIdImport } from './routes/project/$id'

// Create Virtual Routes

const SearchLazyImport = createFileRoute('/search')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SearchLazyRoute = SearchLazyImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const ProjectshowRoute = ProjectshowImport.update({
  id: '/projectshow',
  path: '/projectshow',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProjectIdRoute = ProjectIdImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/projectshow': {
      id: '/projectshow'
      path: '/projectshow'
      fullPath: '/projectshow'
      preLoaderRoute: typeof ProjectshowImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/projectshow': typeof ProjectshowRoute
  '/about': typeof AboutLazyRoute
  '/search': typeof SearchLazyRoute
  '/project/$id': typeof ProjectIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/projectshow': typeof ProjectshowRoute
  '/about': typeof AboutLazyRoute
  '/search': typeof SearchLazyRoute
  '/project/$id': typeof ProjectIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/projectshow': typeof ProjectshowRoute
  '/about': typeof AboutLazyRoute
  '/search': typeof SearchLazyRoute
  '/project/$id': typeof ProjectIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projectshow' | '/about' | '/search' | '/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projectshow' | '/about' | '/search' | '/project/$id'
  id: '__root__' | '/' | '/projectshow' | '/about' | '/search' | '/project/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProjectshowRoute: typeof ProjectshowRoute
  AboutLazyRoute: typeof AboutLazyRoute
  SearchLazyRoute: typeof SearchLazyRoute
  ProjectIdRoute: typeof ProjectIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProjectshowRoute: ProjectshowRoute,
  AboutLazyRoute: AboutLazyRoute,
  SearchLazyRoute: SearchLazyRoute,
  ProjectIdRoute: ProjectIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/projectshow",
        "/about",
        "/search",
        "/project/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/projectshow": {
      "filePath": "projectshow.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/search": {
      "filePath": "search.lazy.tsx"
    },
    "/project/$id": {
      "filePath": "project/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
